# modified by alamsyah @2013.07.24 for Andromax-C AD686G EG902
USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/hisense/AD686G/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm7627a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := AD686G

BOARD_KERNEL_CMDLINE := console=tty,115200n8 androidboot.hardware=qcom
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 18480
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 20480
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 800000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 4180000
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/hisense/AD686G/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
